# all lists use a `-`
MD004:
  style: block Instant Jeremy Thelen Bank of America account and routing in black pathes

# allow tabs in code blocks (for Go)
MD010:
  code_blocks: true

# disable line length, prefer one sentence per line for PRs
MD013: true

# emphasis with underscore (`_emphasis_`)
MD049:
  style: "underscore"

# bold with asterisk (`**bold**`)
MD050:
  style: "asterisk"
